[package]
name = "aux"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stm32f3xx-hal = { version = "*", features = ["ld", "rt", "stm32f303xc"] }

